# Generated by Django 5.2 on 2025-04-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.JSONField(verbose_name='Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
                ('component', models.CharField(blank=True, help_text='System component where the error occurred', max_length=100, null=True, verbose_name='Component')),
                ('context', models.JSONField(blank=True, help_text='Additional context for the error', null=True, verbose_name='Context')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Related Object Type')),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'indexes': [models.Index(fields=['level'], name='core_errorl_level_684160_idx'), models.Index(fields=['component'], name='core_errorl_compone_64f395_idx'), models.Index(fields=['created_at'], name='core_errorl_created_a81460_idx'), models.Index(fields=['resolved'], name='core_errorl_resolve_517393_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(help_text='Type of rate-limited target (e.g., openai, api_endpoint)', max_length=50, verbose_name='Target Type')),
                ('target_id', models.CharField(help_text='Identifier for the rate-limited target', max_length=255, verbose_name='Target ID')),
                ('request_count', models.PositiveIntegerField(default=1, verbose_name='Request Count')),
                ('window_start', models.DateTimeField(verbose_name='Window Start')),
                ('window_end', models.DateTimeField(verbose_name='Window End')),
                ('limit', models.PositiveIntegerField(verbose_name='Limit')),
                ('last_request_at', models.DateTimeField(auto_now=True, verbose_name='Last Request At')),
            ],
            options={
                'verbose_name': 'Rate Limit Log',
                'verbose_name_plural': 'Rate Limit Logs',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_rateli_target__62c835_idx'), models.Index(fields=['window_start', 'window_end'], name='core_rateli_window__8959c8_idx')],
                'unique_together': {('target_type', 'target_id', 'window_start')},
            },
        ),
    ]
