# Generated by Django 5.2 on 2025-04-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_receiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('system_prompt', models.TextField(help_text='System prompt for setting the context', verbose_name='System Prompt')),
                ('user_prompt_template', models.TextField(help_text='Template for user prompt with placeholders', verbose_name='User Prompt Template')),
                ('model', models.CharField(default='gpt-4o', max_length=50, verbose_name='Model')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='Max Tokens')),
                ('function_calling_enabled', models.BooleanField(default=True, verbose_name='Function Calling Enabled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
            },
        ),
        migrations.CreateModel(
            name='FunctionCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=100, verbose_name='Function Name')),
                ('function_arguments', models.JSONField(verbose_name='Function Arguments')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time (s)')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_calls', to='message_receiver.message')),
            ],
            options={
                'verbose_name': 'Function Call Log',
                'verbose_name_plural': 'Function Call Logs',
                'indexes': [models.Index(fields=['function_name'], name='openai_proc_functio_7f683e_idx'), models.Index(fields=['status'], name='openai_proc_status_0ef89a_idx'), models.Index(fields=['created_at'], name='openai_proc_created_7832c3_idx')],
            },
        ),
    ]
