# Generated by Django 5.2 on 2025-04-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('source_type', models.CharField(choices=[('webhook', 'Webhook'), ('api', 'API'), ('email', 'Email'), ('sentry', 'Sentry'), ('whatsapp', 'WhatsApp'), ('custom', 'Custom')], max_length=20, verbose_name='Source Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Source-specific configuration', verbose_name='Configuration')),
                ('webhook_url_path', models.CharField(blank=True, help_text='Path for the webhook endpoint (e.g., sentry-webhook)', max_length=100, null=True, verbose_name='Webhook URL Path')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook Secret')),
                ('prompt_template', models.TextField(blank=True, help_text='Template for OpenAI prompt with placeholders', verbose_name='Prompt Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Message Source',
                'verbose_name_plural': 'Message Sources',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text='Raw message content', verbose_name='Content')),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content for processing', null=True, verbose_name='Content Text')),
                ('external_id', models.CharField(blank=True, help_text='ID from the external system', max_length=255, null=True, verbose_name='External ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='Status Message')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher number means higher priority', verbose_name='Priority')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message_receiver.messagesource')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Prompt')),
                ('openai_response', models.JSONField(blank=True, null=True, verbose_name='OpenAI Response')),
                ('function_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Function Name')),
                ('function_arguments', models.JSONField(blank=True, null=True, verbose_name='Function Arguments')),
                ('api_request', models.JSONField(blank=True, null=True, verbose_name='API Request')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API Response')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Processing Time (s)')),
                ('token_usage', models.JSONField(blank=True, null=True, verbose_name='Token Usage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_result', to='message_receiver.message')),
            ],
            options={
                'verbose_name': 'Processed Message',
                'verbose_name_plural': 'Processed Messages',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source', 'status'], name='message_rec_source__91ce27_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='message_rec_externa_80c2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['received_at'], name='message_rec_receive_5e1882_idx'),
        ),
    ]
